### ISSUE TITLE
this.namespace is null and points api to localhost

### ISSUE THREAD

**Issue by hellsan631** [agilecrm/javascript-api#13]
Running this with angular, and this works and calls the correct api when on my local.

But on production, when creating a new contact in agile, and setting tags, it calls to this url: 

```
http://localhost:8888/core/js/api/contacts?callback=json49788018478453026&id=undefined&contact=%7B%22properties%22%3A%5B%7B%22type%22%3A%22SYSTEM%22%2C%22name%22%3A%22email%22%2C%22value%22%3A%22matkle414%40gmail.com%22%7D%2C%7B%22type%22%3A%22SYSTEM%22%2C%22name%22%3A%22original_ref%22%2C%22value%22%3A%22http%3A%2F%2Fmirror.targetproof.com%2F%22%7D%5D%2C%22tags%22%3A%5B%22Scored%2077%22%2C%22mirror%22%5D%7D&browserId=null&guId=715bcdff-7ee8-fd66-b6d4-76b33ff8f820
```

I think this is due to "this.namespace" the url builder that is in place. it tries to find this.namespace, which is undefined, and this points the script to localhost instead of agilecrm.com.

I'm using the latest script via your CDN, and with essentially a copy paste of what is listed below.

**Comment by graut** [comment]
Hi @hellsan631,

Could you please share code spinet, So I can check and assist you to fix the issue.

**Comment by hellsan631** [comment]
Here is the code, but i don't know how much this will help.

Going to this url:
http://mirror.targetproof.com/report/5891607d12b37900110926ea

i get this error:
![image](https://i.gyazo.com/e4ef0bcbece2de5435307ea1d239f437.png)


and here is the code that is executed upon doing so
```html
<script id="_agile_min_js" src="https://targetproof.agilecrm.com/stats/min/agile-min.js"></script> 
    <script type="text/javascript"> 
      var Agile_API = Agile_API || {};
      Agile_API.on_after_load = function () { 
        _agile.set_account('accountidthing', 'targetproof'); 
        _agile.track_page_view(); 
        _agile_execute_web_rules(); 
      };
    </script>
```

```js
 let tags = `Scored ${Math.floor((report.outcome.scored/report.outcome.possible)*100)}, mirror`;

      if (!report.dmarc.passed) {
        tags += ', no dmarc';
      }

      if (!report.spf.passed) {
        tags += ', no spf';
      }

      if (!report.dkim.passed) {
        tags += ', no dkim';
      }

      _agile.create_contact({
        email: audit.email,
        tags: tags
      },{
        success: function (data) {
          console.log("success");
        },
        error: function (data) {
          console.log("error");
        }
      });

      _agile.set_email(audit.email);
```

**Comment by graut** [comment]
Hi @hellsan631,

Please check below link which has sample form example which will work with your JS API information.

https://github.com/agilecrm/javascript-api/blob/master/create_contact.html

Please follow step as below -

1 . Keep Agile CRM API analysis code and javascript code just above </body>
2. keep  _agile.create_contact method inside some function and call that, It would help you to modify code in future.

Please test in local and production and let me know.

Thanks

**Comment by hellsan631** [comment]
Sorry, i had a post here that went into more details, but was deleted.

If you go to this url, this is where the error occurs:

http://mirror.targetproof.com/report/5891607d12b37900110926ea
![image](https://i.gyazo.com/03d368b673d757a5630c02575c450603.png)

Here is the code: 
```html
<script id="_agile_min_js" src="https://targetproof.agilecrm.com/stats/min/agile-min.js"> </script> 
<script type="text/javascript"> 
  var Agile_API = Agile_API || {};
  Agile_API.on_after_load = function () { 
    _agile.set_account('someidnumber', 'targetproof'); 
    _agile.track_page_view(); 
    _agile_execute_web_rules(); 
  }; 
</script>
```
```js
let tags = `Scored ${Math.floor((report.outcome.scored/report.outcome.possible)*100)}, mirror`;

if (!report.dmarc.passed) {
  tags += ', no dmarc';
}

if (!report.spf.passed) {
  tags += ', no spf';
}

if (!report.dkim.passed) {
  tags += ', no dkim';
}

_agile.create_contact({
  email: email,
  tags: tags
},{
  success: function (data) {
    console.log("success");
  },
  error: function (data) {
    console.log("error");
  }
});

_agile.set_email(email);
```

**Comment by graut** [comment]
Hi @hellsan631, 

I am removing your code from git hub as it contain some security information. Please mail me same at below mail ID, I will assist you through mail.

ghanshyam@agilecrm.com

thanks

**Comment by hellsan631** [comment]
So it seems that this happens only in angular (which is where the tags need to be set). Even when I move it out into a global variable, im still getting this error. the error is caused because its trying to reach a localhost api.

It looks like there was a problem with the on_after_load function not being called, and I had to set the account again inside of the angular factory

```js
_agile.set_account('your_js_key', 'namespace'); 
```

Its working now

**Comment by shjacobs303** [comment]
It also happens in React, thanks @hellsan631, I used the same approach to resolve in my situation.
