### ISSUE TITLE
Option to set contact, deal or task owner

### ISSUE THREAD

**Issue by cainaf** [agilecrm/javascript-api#15]
Is there a way to set contact, deal or task owner?

**Comment by graut** [comment]
Hi @cainaf ,

Do you mean to change owner name for a contact,deal or task ?

**Comment by cainaf** [comment]
Yes! Preferably when creating the contact deal or task as in
`create_contact`, `add_deal` and `addTask`. Every deal or task I create via
JS api is automatically assigned to my user as owner, but I would like to
be able to assign deals to other users. Tasks too.

Em Qua, 15 de mar de 2017 00:44, graut <notifications@github.com> escreveu:

**Comment by graut** [comment]
Hi @cainaf ,

No it is not possible using Javascript API. But you can do it using other back end language (java,php,c# etc).

Reference - 

https://github.com/agilecrm/rest-api#117-change-contact-owner

https://github.com/agilecrm/rest-api#33-create-deal

https://github.com/agilecrm/rest-api#54-create-a-task

**Comment by cainaf** [comment]
Hello @graut. I'll be using the `change-owner` from the rest api then.  Thank you for your reply!

**Comment by askdesigners** [comment]
Can you please make some example of how to update the owner of a deal? I mean I could guess at it but that frankly blows. In the examples of fetching deals it returns an object in the owner field. Do I just pass it an Agile User ID for the owner? An email? A DNA sample?

I have a hard time believing that in your company with dozens of employees you are not able to write better documentation...
