### ISSUE TITLE
 custom fields are not updating from script

### ISSUE THREAD

**Issue by vsatishkumar91** [agilecrm/javascript-api#2]
I am using AgileCRM for creating contacts from agile javascript.
I need two custom fields in my contact information. 
So I created two custom fields, one is list and another one is text.
From the website I am able to update my custom fields, 
But when I am trying to create a contact with custom fields, those are not updating.
Scenario :
I created two fields one is Department as list with values (developing; supporting, Auditing; production;DBA) and another one is Employee code as text
When I try to add contact I just use below code :
var contact = {}; 
contact.email = "contact@test.com"; 
contact.first_name = "Test"; 
contact.last_name = "Contact"; 
contact.company = "abc corp"; 
contact.title = "lead"; 
contact.phone = "+1-541-754-3010"; 
contact.website = "http://www.example.com"; 
var address = {"city":"new delhi", "state":"delhi", "country":"india"}; 
contact.address = JSON.stringify(address); 
contact.tags = "tag1, tag2";
_agile.create_contact(contact, { 
success: function (data) { 
console.log("success"); 
}, 
error: function (data) { 
console.log("error"); 
} 
});
Then it is working fine. 
But if I modify code as
var contact = {};
contact.email = "contact@test.com";
contact.first_name = "Test";
contact.last_name = "Contact";
contact.company = "abc corp";
contact.title = "lead";
contact.phone = "+1-541-754-3010";
contact.Department = " developing ";
contact.phone = "Tech12SE021"
contact.website = "http://www.example.com";
var address = {"city":"new delhi", "state":"delhi", "country":"india"};
contact.address = JSON.stringify(address);
contact.tags = "tag1, tag2";
_agile.create_contact(contact, {
success: function (data) {
console.log("success");
},
error: function (data) {
console.log("error");
}
});
It is not updating in my contact.
Now I change my custom fields to compulsory, then also it is not updating, and also It is not displaying any error message for absent of compulsory fields.
Any help would be greatly appreciated!

**Comment by aDaneInSpain** [comment]
Please update your documentation to reflect this. The information about setting custom fields should be moved from section 2.5 to 2.4 in your documentation. It is currently wrong and does not work as documented.

**Comment by karthikagile** [comment]
Hi @aDaneInSpain 

- We can _set_ custom fields related to contact (i.e custom contact properties) using both **_agile.update_contact** documented under **section 2.4**  (https://github.com/agilecrm/javascript-api/blob/master/README.md#24-update-contact) and **_agile.set_property** documented under **section 2.5** (https://github.com/agilecrm/javascript-api/blob/master/README.md#25-set-contact-property)

- *_agile.update_contact* allows to set multiple custom fields in single API call, but does not support **type**, whereas *_agile.set_property* can be used to set single custom field with **type**

- Checked related documentation, it is correct and up to date.
